home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.ShowHome.as_view(), name="home"),
    path("activities/", views.ShowActivities.as_view(), name="activities"),
]

info/urls.py
from os import name
from django.urls import path ,include
from django.views.decorators.http import require_POST
from . import views


app_name = "info"


urlpatterns = [
    # path("add/", views.AddPhoneNumber.as_view(), name="add_info"),
    # path("show/", views.ShowPhoneNumbers.as_view(), name="show_info"),
    # path("update/", require_POST(views.EditPhoneNumber.as_view()), name="update"),
    # path('delete/<int:pk>/', require_POST(views.DeletePhoneNumber.as_view()), name='delete_phone_number'),
    # path("search/", views.SearchPhoneNumber.as_view(), name="search"),
    # path('download-phone-book/', views.DownloadPhoneBook.as_view(), name='download-phone-book'),

    path('phone-book/add/', views.CreatePhoneNumbers.as_view(), name='add'),
    path('phone-book/list/', views.ListPhoneNumbers.as_view(), name='list'),
    path('phone-book/update/', views.UpdatePhoneNumbers.as_view(), name='update'),
    path('phone-book/delete/<int:pk>/', views.DeletePhoneNumbers.as_view(), name='delete'),
    path("phone-book/search/", views.SearchPhoneNumbers.as_view(), name="search"),
    path('phone-book/download/', views.DownloadPhoneNumberRest.as_view(), name='download')
]

phonebook_project/urls.py
from info import models, views
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from rest_framework.routers import DefaultRouter


router = DefaultRouter()


router.register(prefix=r"", viewset=views.PhoneNumberViewSet, basename="phone-book")


urlpatterns = [
    path("", include("home.urls", namespace="home")),
    path('admin/', admin.site.urls),
    path("info/", include("info.urls", namespace="user_info")),
    path("user/", include("users.urls", namespace="user_login"))
]

urlpatterns += [
    path('api/user-auth/', include('rest_framework.urls')),
    path("api/phone-book/", include(router.urls), name='phone_book'),
]


if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

info/models.py
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import ForeignKey
from django.utils.translation import gettext_lazy as _


phone_regex = RegexValidator(regex='^0[0-9]{2,}[0-9]{7,}$', message='phone number invalid')


class PhoneBook(models.Model):
    auto_increment_id = models.AutoField(primary_key=True, verbose_name=_("Auto Increment Id"))
    user = ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("User"))
    first_name = models.CharField(max_length=25, verbose_name=_("First Name"))
    last_name = models.CharField(max_length=25, verbose_name=_("Last Name"))
    phone_number = models.CharField(verbose_name=_("Phone Number"), max_length=11, validators=[phone_regex])
    created_time = models.DateTimeField(verbose_name=_("Created Time"), auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

info/forms.py
from django import forms
from . import models


class AddInfoFrom(forms.ModelForm):
    class Meta:
        model = models.PhoneBook
        fields = ["first_name", "last_name", "phone_number"]

info/views.py
from django.utils import decorators
from info import forms, models, statics_func, serializers as info_serializers
from info import permissions as info_permissions

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.http import JsonResponse, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView, DeleteView
from django.utils.encoding import smart_str
from django.core import serializers as django_serializers

from rest_framework import status, viewsets, filters, decorators
from rest_framework import permissions as rest_permissions
from rest_framework.response import Response
from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.exceptions import ValidationError
from rest_framework import pagination

import csv, json, logging, weasyprint, json
from collections import defaultdict


logger = logging.getLogger(__name__)


# RestAPI Views with templates --------------------------------------------------------------


class ListPhoneNumbers(LoginRequiredMixin, generics.ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    queryset = models.PhoneBook.objects.all()
    serializer_class = info_serializers.PhoneNumberSerializer
    pagination_class = pagination.PageNumberPagination
    template_name = "show_and_edit.html"

    def get(self, request, *args, **kwargs):
        qs = self.filter_queryset(self.get_queryset())

        return Response(
        {
            "object_list": self.get_paginated_list(qs),
            "page_obj": self.get_page_obj(),
            "paginator": self.get_paginator(),
            "num_pages": self.get_page_range()
        })

    def filter_queryset(self, queryset):
        qs = super().filter_queryset(queryset)
        qs = qs.filter(user=self.request.user)
        return qs

    def get_paginated_list(self, queryset):
        return self.paginate_queryset(queryset)

    def get_page_obj(self):
        return self.paginator.page
    
    def get_paginator(self):
        return self.paginator.page.paginator
    
    def get_page_range(self):
        return range(1, self.paginator.page.paginator.num_pages+1)


class CreatePhoneNumbers(LoginRequiredMixin, generics.ListCreateAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    queryset = models.PhoneBook.objects.all()
    serializer_class = info_serializers.PhoneNumberSerializer

    def get(self, request, *args, **kwargs):
        return Response(
            {
                'serializer': self.get_serializer()
            },
            template_name = "add_info.html"
        )
    
    def create(self, request, *args, **kwargs):
        if statics_func.phone_number_exists_or_not(request):
            try:
                resp = super().create(request, *args, **kwargs)
            except ValidationError:
                return JsonResponse(
                    {
                        "detail": "fields required",
                        "result": False
                    }, status=status.HTTP_400_BAD_REQUEST
                )

            return JsonResponse(
                {
                    "messages": "Your information successfully saved",
                    "new_info_row": resp.data,
                    "result": True
                },
                status=status.HTTP_200_OK
            )
        else:
            return JsonResponse(
                {
                    "detail": "Your phone already exists",
                    "result": False
                }, 
                status=status.HTTP_409_CONFLICT)


class UpdatePhoneNumbers(LoginRequiredMixin, generics.UpdateAPIView):
    queryset = models.PhoneBook.objects.all()
    serializer_class = info_serializers.PhoneNumberSerializer

    def get_object(self, queryset=None):
        pk = self.request.GET.get("pk", None)
        if pk:
            if pk.isdigit():
                user = self.request.user
                phone_obj = get_object_or_404(klass=models.PhoneBook, pk=pk)

                if user == phone_obj.user:
                    return phone_obj
                else:
                    raise Http404
            else:
                raise Http404
        else:
            raise Http404

    def update(self, request, *args, **kwargs):
        if statics_func.phone_number_exists_or_not(request):
            try:
                super().update(request, *args, **kwargs)
            except ValidationError:
                return JsonResponse(
                    {
                        "message": "fields required or they are not valid",
                        "result": False
                    }, status=status.HTTP_400_BAD_REQUEST
                )

            return JsonResponse(
                {
                    'message': "You've successfully edited",
                    'result': True
                }, status=status.HTTP_200_OK)
        else:
            return JsonResponse(
                {
                    'message': "phone number already exists",
                    'result': False
                }, status=status.HTTP_422_UNPROCESSABLE_ENTITY)


class DeletePhoneNumbers(LoginRequiredMixin, generics.DestroyAPIView):
    queryset = models.PhoneBook.objects.all()
    serializer_class = info_serializers.PhoneNumberSerializer

    def delete(self, request, *args, **kwargs):
        super().delete(request, *args, **kwargs)

        return JsonResponse(
                {
                    'message': "You've successfully deleted"
                }, status=status.HTTP_200_OK)


class SearchPhoneNumbers(LoginRequiredMixin, generics.ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    queryset = models.PhoneBook.objects.all()
    serializer_class = info_serializers.PhoneNumberSerializer
    template_name = "search.html"

    def get(self, request, *args, **kwargs):
        qs = self.filter_queryset(self.get_queryset())
        lst_values = list(qs)
        
        if request.query_params:
            results = []
            data = django_serializers.serialize('json', qs)
            data = json.loads(data)

            for item in data:
                results.append(item['fields'])

            return JsonResponse(
                {
                    'results': results,
                    'results_count': len(results)
                }, status=status.HTTP_200_OK)
        else:
            return Response(
                {
                    "object_list":  lst_values,
                },status=status.HTTP_200_OK)
    
    def filter_queryset(self, queryset):
        qs = super().filter_queryset(queryset)
        qs = qs.filter(user=self.request.user)

        if self.request.query_params:
            phone_number_input = self.request.GET.get('phone_number', None)
            radio_box_number = self.request.GET['checked_radio_box_number']

            if radio_box_number == "1":
                qs = qs.filter(phone_number=phone_number_input)
            elif radio_box_number == "2":
                qs = qs.filter(phone_number__startswith=phone_number_input)
            elif radio_box_number == "3":
                qs = qs.filter(phone_number__endswith=phone_number_input)
            else:
                qs = qs.filter(phone_number__contains=phone_number_input)

        return qs


class DownloadPhoneNumberRest(LoginRequiredMixin, generics.ListAPIView):
    queryset = models.PhoneBook.objects.all()
    serializer_class = info_serializers.PhoneNumberSerializer

    def filter_queryset(self, queryset):
        qs = super().filter_queryset(queryset)
        qs = qs.filter(user=self.request.user)
        return qs

    def get(self, request, *args, **kwargs):
        qs = self.filter_queryset(self.get_queryset())
        phone_numbers = django_serializers.serialize('json', qs)
        phone_numbers_list = json.loads(phone_numbers)

        # create response with text/csv MIME
        response = HttpResponse(content_type='text/csv')

        # the Content-Disposition is a header indicating if the content is expected to be as an attachment, that is downloaded and saved locally
        response['Content-Disposition'] = 'attachment; filename="phone_numbers.csv"'

        # respose is like open(filename) for writer
        # csv.excel is the type we want to write in response -> the way we want to behave with response
        csv_writer = csv.writer(response, csv.excel)

        # excel needs this line to open UTF-8 file properly (correctly)
        response.write(u'\ufeff'.encode('utf8'))

        # writing headers
        csv_writer.writerow([
            smart_str(u"first_name"),
            smart_str(u"last_name"),
            smart_str(u"phone_number")
        ])

        # writing rows
        for phone_number in phone_numbers_list:
            row = []
            row.append(phone_number['fields']['first_name'])
            row.append(phone_number['fields']['last_name'])
            row.append(phone_number['fields']['phone_number'])
            csv_writer.writerow(row)

        # return created csv file in response for downloading
        return response


# RestAPI Views with ModelViewSet --------------------------------------------------------------


class PhoneNumberViewSet(viewsets.ModelViewSet):

    search_fields = ['phone_number', 'first_name', 'last_name', ]
    filter_backends = (filters.SearchFilter,)
    queryset = models.PhoneBook.objects.all()
    serializer_class = info_serializers.PhoneNumberSerializer
    permission_classes = [rest_permissions.IsAuthenticated, info_permissions.PhoneNumberCreatorOrNot]

    def create(self, request, *args, **kwargs):
        """Create User Object With API"""

        if statics_func.phone_number_exists_or_not(request):
            return super().create(request, *args, **kwargs)
        else:

info/templates/add_info.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load  rest_framework %}

{% block title %} {% trans "Add You Info" %} {% endblock %}

{% block content %}
    <div class="row">
        <div class="p-lg-4">
            <p id="message"></p>
        </div>
        <div class="col-12">
            <div style="margin-left: 35%; margin-right: 35%; margin-top: 5%;">
                <h4 class="text-white fw-bold">{% trans "Add Form" %}</h4>
                <form>
                    {% csrf_token %}
                    {% render_form serializer %}
                </form>
                <div class="text-center">
                    <button id="submit-button" class="btn-primary text-white">{% trans "Submit" %}</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block page_scripts %}
    <script>

        function changeInputBorderColor(event) {
            let input_target = $(event.target);
            input_target.removeAttr("style");
            input_target.removeAttr("placeholder");
        }

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $(document).ready(
            function () {
                let submit_button_selector = $("#submit-button");
                let message_p_tag_selector = $("#message");


                submit_button_selector.click(
                    function () {

                        // let first_name = $("#first_name")[0].value;

                        const csrftoken = getCookie('csrftoken');
                        let digit = new RegExp('^[0-9]+$');
                        let first_name_selector = $("[name=first_name]");
                        let last_name_selector = $("[name=last_name]");
                        let phone_number_selector = $("[name=phone_number]");
                        let first_name_value = first_name_selector.val();
                        let last_name_value = last_name_selector.val();
                        let phone_number_value = phone_number_selector.val();

                        if (digit.test(phone_number_value)) {

                            // connect to server and get response
                            $.ajax(
                                {
                                    url: "{% url "info:add" %}",

                                    headers: {'X-CSRFToken': csrftoken},

                                    method: "POST",

                                    mode: 'same-origin',

                                    data: {
                                        first_name: first_name_value,
                                        last_name: last_name_value,
                                        phone_number: phone_number_value,
                                    },

                                    success:
                                        function (response) {
                                            let messages = response["messages"]
                                            let result = response["result"]

                                            if (result) {
                                                // message_p_tag_selector.html(messages);
                                                alert(messages)

                                                //add new row to the search table that is in search template
                                                $(response["new_info_row"]).each(
                                                    function (index, obj) {
                                                        let output_tbl = $("#output-tbl");

                                                        let my_table_data =
                                                            "<tr class='dynamic'><td>" + obj.first_name + "</td>" +
                                                            "<td>" + obj.last_name + "</td>" +
                                                            "<td>" + obj.phone_number + "</td></tr>"

                                                        $(output_tbl).append(my_table_data);
                                                    })

                                            } 
                                            
                                            else {
                                                // show errors in input fields
                                                let name_attr;
                                                for (let i = 0; i < messages.length; i++) {
                                                    for (name_attr in messages[i]) {
                                                        let input_selector = $("#" + name_attr);
                                                        let message = messages[i][name_attr];

                                                        input_selector[0].setAttribute("style", "border-color:red");
                                                        input_selector[0].setAttribute("placeholder", message);
                                                    }
                                                }
                                            }

                                            first_name_selector.val("");
                                            last_name_selector.val("");
                                            phone_number_selector.val("");
                                    },

                                    error:
                                        function (errors) {
                                            alert(errors.responseJSON['detail']);
                                    }
                                }
                            )
                        } else {
                            alert("phone number have to be digit.");
                        }

                    }
                )
            }
        )
    </script>
{% endblock %}

info/templates/download_phone_number_page.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
    <div style='margin-top: 100px; margin-right: 50px; margin-left: 50px;'>
        <table class="table table-info table-striped table-hover text-center">
            <tr>
                <td colspan="3">{% trans "Added Phone Number" %}</td>
            </tr>
            <tr>
                <th>{% trans "First Name" %}</th>
                <th>{% trans "Last Name" %}</th>
                <th>{% trans "Phone Number" %}</th>
            </tr>
            {% for row in object_list %}
                <tr id="{{ row.pk }}">
                    <td>{{ row.first_name }}</td>
                    <td>{{ row.last_name }}</td>
                    <td><p>{{ row.phone_number }}</p></td>
                </tr>
            {% endfor %}
        </table>
{% endblock content %}

info/templates/show_and_edit.html
{% extends "base.html" %}
{% load i18n %}
{% load phonebook_custom_tags %}


{% block style %}
    <style>
        .pagination > li > a {
            background-color: white;
            color: orangered;
        }

        .pagination > li > a:focus,
        .pagination > li > a:hover,
        .pagination > li > span:focus,
        .pagination > li > span:hover {
            color: orangered;
            background-color: orange;
            border-color: coral;
        }

        .pagination > .active > a {
            color: white;
            background-color: darkorange !Important;
            border: solid 1px lightcoral !Important;
        }

        .pagination > .active > a:hover {
            background-color: yellow !Important;
            border: solid 1px orange;
        }
    </style>
{% endblock %}

{% block content %}
    <div class='text-center fs-5' style="margin-top: 100px;">
        <a type='button' href="{% url 'info:download' %}" style='text-decoration: none; color:white;' class='btn btn-primary'>
            {% trans "Download" %}  <i class="fa fa-download"></i>
        </a>
    </div>
    <div style="padding-right: 200px; padding-left: 200px;padding-top: 40px;">
        <table id="output-tbl" class="table table-info table-striped table-hover text-center">
            <tr>
                <td colspan="5">{% trans "Added Phone Number" %}</td>
            </tr>
            <tr class="static">
                <th>{% trans "First Name" %}</th>
                <th>{% trans "Last Name" %}</th>
                <th>{% trans "Phone Number" %}</th>
                <th>{% trans "Edit" %}</th>
                <th>{% trans "Delete" %}</th>
            </tr>
            {% for row in object_list %}
                <tr id="{{ row.pk }}" class="static">
                    <td>{{ row.first_name }}</td>
                    <td>{{ row.last_name }}</td>
                    <td>
                        <p>
                            {% if request.LANGUAGE_CODE == 'fa' %}
                                {{ row.phone_number|convert_to_persion_number:'fa' }}
                            {% else %}
                                {{ row.phone_number|convert_to_persion_number:'en' }}
                            {% endif %}
                        </p>
                        <form id="phone_form" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>
                                    <input class="input_phone" type="text" maxlength="11" disabled="disabled">
                                </label>
                            </div>
                        </form>
                        <button class="submit btn btn-primary disabled mt-3" onclick="submitButtonFunction(event)"
                                data-id="{{ row.pk }}"> <i class='fa fa-check-circle'></i> {% trans "Submit" %}
                        </button>
                    </td>
                    <td>
                        <button class="edit btn btn-primary mt-4" data-id="{{ row.pk }}" onclick="editButtonFunction(event)">
                                <i class="fa fa-edit"></i> {% trans "Edit" %}
                        </button>
                    </td>
                    <td>
                        <form>
                            {% csrf_token %}
                        </form>
                        <button id='delete-btn' class='btn btn-primary mt-lg-4 text-white' onclick='deletePhoneNumber(event)'
                            data-href="{% url 'info:delete' row.pk %}" data-id="{{ row.pk }}">
                            <i class='fa fa-trash'></i> {% trans "Delete" %}
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        {% trans "First" %}
                    </a>
                </li>
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for i in num_pages %}
                    {% if page_obj.number == i %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ i }}">
                                {% if request.LANGUAGE_CODE == 'fa' %}
                                    {{ i|convert_to_persion_number:'fa' }}
                                {% else %}
                                    {{ i|convert_to_persion_number:'en' }}
                                {% endif %}
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">
                                {% if request.LANGUAGE_CODE == 'fa' %}
                                    {{ i|convert_to_persion_number:'fa' }}
                                {% else %}
                                    {{ i|convert_to_persion_number:'en' }}
                                {% endif %}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ paginator.num_pages }}">
                        {% trans "Last" %}
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

{% block page_scripts %}
    <script>

        let trs = {};

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        function editButtonFunction(event) {
            let input_elm, submit_btn, chosen_row_id, tr;

            chosen_row_id = event.currentTarget.dataset["id"];
            tr = $("#" + chosen_row_id);

            input_elm = tr.find(".input_phone");
            submit_btn = tr.find(".submit");

            submit_btn.removeClass("disabled");
            input_elm.removeAttr("disabled");

            trs[chosen_row_id] = tr;
        }

        function deletePhoneNumber(event) {
            href_row = event.currentTarget.dataset["href"];
            chosen_row_id = event.currentTarget.dataset["id"];
            tr = $("#" + chosen_row_id);
            csrf_token = getCookie('csrftoken');

            $.ajax(
                {
                    url: href_row,

                    headers: {'X-CSRFToken': csrf_token},

                    method: 'delete',

                    dataType: 'json',

                    success: function(response) {
                        alert(response['message']);
                        $(tr).remove();
                    }
                }
            )
        }

        function submitButtonFunction(event) {
            let input_elm, submit_btn, chosen_row_id, tr;
            let csrf_token, p_elm, new_phone_number;

            chosen_row_id = event.currentTarget.dataset["id"];
            tr = trs[chosen_row_id];
            p_elm = tr.find("p")
            csrf_token = getCookie('csrftoken');
            input_elm = tr.find(".input_phone");
            submit_btn = tr.find(".submit");
            new_phone_number = input_elm.val();

            $.ajax(
                {
                    url: "{% url 'info:update' %}" + "?pk=" + chosen_row_id,

                    headers: {'X-CSRFToken': csrf_token},

                    method: "PATCH",

                    data: {
                        phone_number: new_phone_number
                    },

                    success: function (response) {
                        p_elm.html(new_phone_number);
                        alert(response.responseJSON['message']);
                    },

                    error: function (response) {
                        alert(response.responseJSON['message']);
                    }
                }
            )

            input_elm.attr("disabled", "disabled");
            submit_btn.addClass("disabled");
            input_elm.val("");
        }

        //$(document.ready(function () {} ));
        //$(function (){});

    </script>
{% endblock %}