home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.ShowHome.as_view(), name="home"),
    path("activities/", views.ShowActivities.as_view(), name="activities"),
]

info/urls.py
from os import name
from django.urls import path ,include
from django.views.decorators.http import require_POST
from . import views


app_name = "info"


urlpatterns = [
    # path("add/", views.AddPhoneNumber.as_view(), name="add_info"),
    # path("show/", views.ShowPhoneNumbers.as_view(), name="show_info"),
    # path("update/", require_POST(views.EditPhoneNumber.as_view()), name="update"),
    # path('delete/<int:pk>/', require_POST(views.DeletePhoneNumber.as_view()), name='delete_phone_number'),
    # path("search/", views.SearchPhoneNumber.as_view(), name="search"),
    # path('download-phone-book/', views.DownloadPhoneBook.as_view(), name='download-phone-book'),

    path('phone-book/add/', views.CreatePhoneNumbers.as_view(), name='add'),
    path('phone-book/list/', views.ListPhoneNumbers.as_view(), name='list'),
    path('phone-book/update/', views.UpdatePhoneNumbers.as_view(), name='update'),
    path('phone-book/delete/<int:pk>/', views.DeletePhoneNumbers.as_view(), name='delete'),
    path("phone-book/search/", views.SearchPhoneNumbers.as_view(), name="search"),
    path('phone-book/download/', views.DownloadPhoneNumberRest.as_view(), name='download')
]

phonebook_project/urls.py
from info import models, views
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from rest_framework.routers import DefaultRouter


router = DefaultRouter()


router.register(prefix=r"", viewset=views.PhoneNumberViewSet, basename="phone-book")


urlpatterns = [
    path("", include("home.urls", namespace="home")),
    path('admin/', admin.site.urls),
    path("info/", include("info.urls", namespace="user_info")),
    path("user/", include("users.urls", namespace="user_login"))
]

urlpatterns += [
    path('api/user-auth/', include('rest_framework.urls')),
    path("api/phone-book/", include(router.urls), name='phone_book'),
]


if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.LogoutUser.as_view(), name="logout"),
]

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html {% if request.LANGUAGE_CODE == 'fa' %} lang='fa' dir='rtl' {% else %} lang='en' dir='ltr' {% endif %}>
<head>
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href={% static "bootstrap_cdn/css/bootstrap.css" %}>
    <link rel="stylesheet" href={% static "bootstrap_cdn/css/bootstrap.min.css" %}>
    <link rel="stylesheet" type="text/css" href="{% static "fontawesome/css/all.min.css" %}"/>
    <link rel="stylesheet"  href="{% static "css-style/style.css" %}"/>
</head>

<style>
    {% block style %}{% endblock %}
</style>

<body style="background-image:url('{% static "images/phone_book.png" %}');">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "home:home" %}">
            <i class="fa fa-address-book"></i> {% trans "Phone Book" %}
        </a>
        {% comment %} <p class='text-white mt-3'>
            <a class="navbar-brand" href="{{ request.path }}?lang=en"><i class=""></i> {% trans "English" %}</a>
            <a class="navbar-brand" href="{{ request.path }}?lang=fa"><i class=""></i> {% trans "Persian" %}</a>
        </p> {% endcomment %}
        {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url "home:home" %}">
                <i class="fa fa-user"></i> {{ request.user.username }}
            </a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item navbar-light">
                    <a class="nav-link text-white active" aria-current="page" href="{% url "home:home" %}">
                        <i class="fa fa-home"></i> {% trans "Home" %}
                    </a>
                </li>
                {% if not request.user.is_authenticated %}
                    <li class="nav-item navbar-light">
                        <a class="nav-link text-white active" aria-current="page"
                           href="{% url "user:login" %}">
                           <i class="fa fa-sign-in-alt"></i> {% trans "Login" %}
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item navbar-light">
                        <a class="nav-link text-white active" aria-current="page"
                           href="{% url "user:logout" %}">
                           <i class="fa fa-sign-out-alt"></i> {% trans "Logout" %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white active" href="{% url "home:activities" %}">
                            <i class="fa fa-history"></i> {% trans "Activities" %}
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link text-white active" href="{% url "info:search" %}">
                        <i class="fa fa-search"></i> {% trans "Search" %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white active" href="{% url "info:add" %}">
                        <i class="fa fa-plus-circle"></i> {% trans "Add" %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url "info:list" %}">
                        <i class="fa fa-eye"></i> {% trans "Show" %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<script src={% static "bootstrap_cdn/js/bootstrap.js" %}></script>
<script src={% static "bootstrap_cdn/js/bootstrap.min.js" %}></script>
<script src={% static "jquery/jquery-3.6.0.min.js" %}></script>

{% block page_scripts %}{% endblock %}

</body>
</html>

templates/pagination.html
{% load i18n %}
{% load phonebook_custom_tags %}


{% block content %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="?page=1">
                    {% trans "First" %}
                </a>
            </li>
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ i }}">
                            {% if request.LANGUAGE_CODE == 'fa' %}
                                {{ i|convert_to_persion_number:'fa' }}
                            {% else %}
                                {{ i|convert_to_persion_number:'en' }}
                            {% endif %}
                        </a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">
                            {% if request.LANGUAGE_CODE == 'fa' %}
                                {{ i|convert_to_persion_number:'fa' }}
                            {% else %}
                                {{ i|convert_to_persion_number:'en' }}
                            {% endif %}
                        </a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
            <li class="page-item">
                <a class="page-link" href="?page={{ paginator.num_pages }}">
                    {% trans "Last" %}
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}